{
 "title": "WSO2 API Logs",
 "tags": [ "wso2" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "API",
    "label": "API",
    "query": {}
   },
   {
    "name": "CorrelationID",
    "label": "CorrelationID",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (statusCode) (count_over_time({job=\"api.log\", statusCode=~\".+\", apiTo=~\"$API\", correlationId=~\"$CorrelationID\"} [24h]))"
    }
   ]
  },
  {
   "title": "Top APIs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (apiTo) (count_over_time({job=\"api.log\", apiTo=~\".+\"}[24h])))"
    }
   ]
  },
  {
   "title": "Top StatusCodes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(statusCode) (count_over_time({job=\"api.log\", statusCode=~\".+\", apiTo=~\"$API\", correlationId=~\"$CorrelationID\"} [24h]))"
    }
   ]
  },
  {
   "title": "Top Sources",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(sourceIP) (rate({job=\"api.log\", apiTo=~\"$API\", correlationId=~\"$CorrelationID\"} | json sourceIP=\"sourceIP\" | sourceIP =~ `.+` [24h]))"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "table",
   "gridPos": { "h": 22, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"api.log\", log_time=~\".+\", apiTo=~\"$API\", correlationId=~\"$CorrelationID\"} |= ``"
    }
   ]
  },
  {
   "title": "Header & Payload",
   "type": "logs",
   "gridPos": { "h": 22, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"api.log\", log_time=~\".+\", apiTo=~\"$API\", correlationId=~\"$CorrelationID\"} | json | __error__=``"
    }
   ]
  }
 ]
}